apiVersion: v1
kind: Pod
metadata:
  name: apigee-client
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx
#    image: registry.container-registry.svc.cluster.local:5000/apigee-client
    image: localhost:32000/apigee-client
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  hostNetwork: true
  dnsPolicy: Default