apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: randomquotes-image
spec:
  type: image
  params:
    - name: url
#      value: localhost:32000/apigee-client
      value: registry.container-registry.svc.cluster.local:5000/apigee-client    